### ISSUE TITLE
Creating new app with template gives error after deploy to FZ

### ISSUE THREAD

**Issue by ASoldo** [flipperzero-rs/flipperzero#133]
Hi, after updating FZ to latest development branch and created demo app i get this error (that ApiTooOld). Firmware Api Version: 58. Anybody know what to do here?
![image](https://github.com/flipperzero-rs/flipperzero/assets/1175537/c6e8f279-3e60-4d77-87fa-e297ce15f4ba)

**Comment by JarvisCraft** [comment]
@ASoldo, hi there!
I've just opened the PR to update to the lastest SDK version: #134.

Please try using its branch and test if it fixes the issue.

**Comment by ASoldo** [comment]
This is what I did but I get the same error message after moving .fap to FZ and running it.
```toml
[dependencies]
flipperzero = { git = "https://github.com/flipperzero-rs/flipperzero", branch = "sdk-0.99.1" }
flipperzero-sys = { version = "0.11.0" }
flipperzero-rt = { version = "0.11.0" }
```

**Comment by JarvisCraft** [comment]
You should also update `-sys` and `rt` references to the same repo

**Comment by ASoldo** [comment]
I did try that but it gives me this error when `cargo build`
```toml
[dependencies]
flipperzero = { git = "https://github.com/flipperzero-rs/flipperzero", branch = "sdk-0.99.1" }
flipperzero-sys = { git = "https://github.com/flipperzero-rs/flipperzero", branch = "sdk-0.99.1" }
flipperzero-rt = { git = "https://github.com/flipperzero-rs/flipperzero", branch = "sdk-0.99.1" }
```
![image](https://github.com/flipperzero-rs/flipperzero/assets/1175537/da6f3ead-8ce3-4932-8a2a-4dfbc279883a)
