### ISSUE TITLE
Error: Outdated App - SDK Upgrade

### ISSUE THREAD

**Issue by Maddox-Werts** [flipperzero-rs/flipperzero#150]
### Hello, Everyone!

I've just updated my Flipper Zero to the latest version of Momentum Firmware. I've also gone ahead and setup a Docker environment to build the application and get everything in order to create the *.FAP* file.

After some Trial and Error, I got Rust to compile to a *.FAP* file. I placed the file on my Flipper Zero's *SD Card* and launched it to get the following message:

![Screenshot-20240810-005302](https://github.com/user-attachments/assets/be3b2b20-9f7e-48c2-8513-f7afac57d523)

Does anyone know how to upgrade the SDK version? Any help would be greatly appreciated.

**Comment by JarvisCraft** [comment]
Hi there and sorry for the late reply!

We are working on update to the latest API in #154 (regenerated bindings) and #155 (additional changes needed in our runtime implementation).

**Comment by bkstephen** [comment]
Any update on this?

**Comment by Maddox-Werts** [comment]
Hey, Bkstephen! 
No, unfortunately not. I was not able to compile it to an updated version of the SDK. I had to write my app in C. I'd recommend you do the same even though Rust is amazing.

**Comment by bkstephen** [comment]
Ok thank you, maybe its worth archiving this project then.

**Comment by str4d** [comment]
No this project will not get archived. We just haven't been able to keep up with the very rapid rate of changes to the Flipper Zero SDK prior to its 1.0 release, so we only generally got updates out that jumped over multiple SDK updates.

[Firmware 1.0 was released today](https://blog.flipper.net/released-firmware-1/), so we will target that for the next update.

**Comment by ASoldo** [comment]
This is what I've been waiting for. No rush, just make it happen eventually. I can't wait to get back to it again!

**Comment by 8de2fdb0** [comment]
@str4d 

if you can't wait use
```toml
[dependencies]
flipperzero = { git = "https://github.com/flipperzero-rs/flipperzero", branch = "update-bindings-1.0" }
flipperzero-sys = {  git = "https://github.com/flipperzero-rs/flipperzero", branch = "update-bindings-1.0"  }
flipperzero-rt = {  git = "https://github.com/flipperzero-rs/flipperzero", branch = "update-bindings-1.0"  }
```

@ASoldo nice work
